server:
  port: 8080
  servlet:
    context-path: /trio_shop_client
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/4?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: 127.0.0.1
    port: 6380
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
  rabbitmq:
    host: 127.0.0.1
    password: guest
    username: guest
    port: 5672
  data:
    mongodb:
      host: 192.168.241.129
      port: 27017
      database: 1804B
  aop:
    auto: true

mybatis:
  mapper-locations: classpath:xml/*.xml
  type-aliases-package: com.jk.model

